### PR TITLE
Convert to patch, use updated trunk

### PR DESCRIPTION
**Pull request by arirusso**
Story: https://www.pivotaltracker.com/n/projects/1106466/stories/84862982

Converts this to a patch and bundles the [trunk version of the gem](http://rubygems.org/gems/minitest-metadata)

Tests are green locally for me

### CODE REVIEW

**Comment by quirkey** [comment]
I mean, codewise it looks good - not sure if you've tested yet, but I had a LOT of problems getting this to work with minitest5 and it was not completely obvious that it wasnt working in certain scenarios. The key to testing is to show that the SAME tests get filtered as p1s etc. If its not working p1 will still run, but will run ALL the tests.

**Comment by arirusso** [comment]
Thanks, the tests on the gem are passing but I haven't run it on a PP build yet.  We'll take it from there...

**Comment by quirkey** [comment]
Yeah, metadata is only used in acceptance tests so you'll only see it there.

**Comment by arirusso** [comment]
Looks like the acceptance tests are working, I'm going to merge this and deploy to earth

**Pull request merged**
